### ISSUE TITLE
Weather events in other dimensions

### ISSUE THREAD

**Issue by Joththeboop** [Talon396/EnhancedWeather#1]
I think it should be configurable in hwat dimensions the weather can occur. I'm using this together with the "Ad Astra!" mod and are getting weather in their dimensions where it doesnt make sense

**Comment by Talon396** [comment]
Hi, @Joththeboop. I seem to be a little confused. Are you saying that the dimensions in the "Ad Astra!" mod don't have any weather, or are you saying that the other dimensions have weather events when there shouldn't be any weather in the other dimensions?

**Comment by Talon396** [comment]
Pull Request was merged, this bug should be fixed in the next update of "Ad Astra!"
