### ISSUE TITLE
JourneyMap support for weather radar

### ISSUE THREAD

**Issue by Steveplays28** [Talon396/EnhancedWeather#12]
**Is your feature request related to a problem? Please describe.**
JourneyMap has a minimap which has an API that probably supports custom overlays.

**Describe the solution you'd like**
A JourneyMap overlay on the minimap/fullscreen map which displays the weather, like there's overlays for the biomes, topology, etc

**Describe alternatives you've considered**
Xaero's Minimap, doesn't have an API and is closed source

**Additional context**
![Weather radar](https://user-images.githubusercontent.com/105325988/197291865-b390fe26-ecd0-4ece-a283-560ec89f3a6c.png)
WIP dev screenshot of weather radar

![image](https://user-images.githubusercontent.com/62797992/197296639-7d69e5b7-3cef-4bd1-a1ab-6f01dacb883e.png)
JourneyMap minimap screenshot

These two images but merged together would be cool!

**Comment by Talon396** [comment]
![Screenshot from 2022-10-21 17-31-01](https://user-images.githubusercontent.com/105325988/197297873-2e938b4d-e9c8-40df-88eb-078a3b13966e.png)
Looks like the API hasn't updated since 1.12...
Not sure if that means that it hasn't changed since then, or if that means it's not possible.

**Comment by Talon396** [comment]
Wait nevermind, looks like it is possible.

**Comment by Talon396** [comment]
@Steveplays28
[Check this out](https://user-images.githubusercontent.com/105325988/197357480-dddecdd5-af1b-4d24-9e46-8d0914463c3c.webm)
(Sorry for the low quality, GitHub only allows files to be up to 10 MiB >_<)

**Comment by Steveplays28** [comment]
:o looks cool! nice work

**Comment by Talon396** [comment]
Thanks! Just curious if there's anything I can approve on. If not I'll push the commit for this and close this issue.

**Comment by Steveplays28** [comment]
Maybe adding a toggle at the top bar of JourneyMap would be nice, not really sure what else at the moment.
Also, is that an overlay for thunder? Or did I interpret that incorrectly?

**Comment by Talon396** [comment]
> Maybe adding a toggle at the top bar of JourneyMap would be nice, not really sure what else at the moment.
I could maybe do that, let me see
> Also, is that an overlay for thunder? Or did I interpret that incorrectly?
The overlay works with all storms, not just thunder, so it's basically the same as the weather radar.

**Comment by Steveplays28** [comment]
Ah okay nice!

**Comment by Talon396** [comment]
Added a button to toggle the overlay.
![2022-10-22_15 50 50](https://user-images.githubusercontent.com/105325988/197361880-bbd87f42-0e24-47d0-849a-5cac7de11699.png)

**Comment by Steveplays28** [comment]
Awesomee! Great work dude, thanks
I'll close the issue then
