### ISSUE TITLE
snow

### ISSUE THREAD

**Issue by oriolprogamer712** [Talon396/EnhancedWeather#16]
1 add one more thing snow effects when falling down the mountains snow blizzard
2 adds realistic snow
3 Here are some photos
4 add a new snow configuration
5...

**Comment by oriolprogamer712** [comment]
![IMG_20221127_202416.jpg](https://user-images.githubusercontent.com/92949450/204155536-255b0ddc-ce45-4d98-89ee-d5e9e7279ae2.jpg)

**Comment by oriolprogamer712** [comment]
![IMG_20221127_202551.jpg](https://user-images.githubusercontent.com/92949450/204155609-4324fd0b-3957-40cb-8e65-fb56a082b14c.jpg)![IMG_20221127_202559.jpg](https://user-images.githubusercontent.com/92949450/204155615-499a50bc-80f8-44e5-9b3f-fa8657cdf3a1.jpg)

**Comment by oriolprogamer712** [comment]
realistic snow

**Comment by oriolprogamer712** [comment]
photos

**Comment by Talon396** [comment]
Umm, I'll think about it.

Also please use the template for suggestions/enhancements next time or I'll instantly close the issue as invalid without looking at it.
