### ISSUE TITLE
Alpha 2 1.20.1 Backport?

### ISSUE THREAD

**Issue by PolyframeX** [Talon396/EnhancedWeather#41]
Would it be possible if a backport of the mod was made for 1.20.1 on Alpha 2? 1.20.1 is a very popular mod version that is currently the only main accessible version right now for many people.

**Comment by XavierEXE** [comment]
Agreed, 1.20.1 is the version I'm on as well ;w;

**Comment by TalonFloof** [comment]
There was a lot of code changes I had to do to get it running on 1.20.4, if I were to backport it to 1.20.1 I'd have to reverse that and create a new branch, it's possible, but it would take a lot of time, and would generally be a nuisance as I'd then have to maintain two branches of the same version of the mod with different Minecraft versions.

I am aware however that 1.20.1 is more widely used in the mod ecosystem, I will consider backporting it, but if you know of any better solution for this other than what I stated, I'd appreciate hearing it from you guys.

**Comment by TalonFloof** [comment]
However, if you guys know of a better solution, I'd be more than happy to hear

**Comment by TalonFloof** [comment]
Backported to 1.20.1 :3
