### ISSUE TITLE
game crashes randomly

### ISSUE THREAD

**Issue by Pigfection** [Talon396/EnhancedWeather#44]
[crash-2024-03-25_16.25.06-server.txt](https://github.com/TalonFloof/EnhancedWeather/files/14739793/crash-2024-03-25_16.25.06-server.txt)
crash-report only mentions enhancedweather, seeing if there might be another issue too

**Comment by Pigfection** [comment]
dont put tornado chance to zero if you dont wanna have this crash

**Comment by TalonFloof** [comment]
I'll still try to fix that @Pigfection, thanks for figuring out why it happens though ^w^

**Comment by Galysso** [comment]
Hey, I had this crash and I also set tornado chances to 0.
I hope this will get fixed :-)
