### ISSUE TITLE
Tornadoes Not Doing Damage?

### ISSUE THREAD

**Issue by ghost** [Talon396/EnhancedWeather#45]
Are tornadoes able to do damage in v1.0 Beta 5.4? When tornadoes spawn in, they only pull the player and animals. Is this not implemented yet or did I install the mod wrong? But anyways the mod is great. I'm personally more of a fan of the v1.0 than 1.1. I feel like once tornado damage gets fixed, this mod will be on par with Weather2 1.20.1. If you do decide to put damage on tornadoes, can you plz put it on 1.0

**Comment by TalonFloof** [comment]
1.0 is discontinued and will not be receiving further updates, due to this, this issue will be closed as it is irrelevant to the latest version of the mod.
