### ISSUE TITLE
User Friendly Config/explanation of config screen

### ISSUE THREAD

**Issue by slavens** [Talon396/EnhancedWeather#67]
I'm another user of Enhanced Weather and Distant Horizons. My opinion is that these two mods are essential for a good MC experience. My 'issue' is that my world is now essentially Seattle - or maybe London.... 

I haven't seen the sun in almost a minecraft month. I started out with varied weather when I installed the mod last Thursday, but now it's constant rain and lightning.

After losing 90% of the village population (of better than 100 villagers) to an EF5 tornado I fiddled with the 'chances' of Supercells (dropped it to 1) and ended up with constant super cell activity. Before this, I had fairly random weather.

I had similar results for Squall Lines. Set to '1', I was even getting multiple squall lines at once. 

I've since returned all settings to default and turned tornadoes off (about an hour ago). I'll give it some time for the weather to normalize, but I expect that this being a coastal village has a lot to do with the weather. 

My issue with trying to tune the weather is that I'm not sure how changing settings affects things. My initial thought was that things labelled 'chance' were a percentage, but lightning's default setting of 25000 hints that this isn't the case.

Can you add tool tips or something that indicates min and max settings and how the setting should impact the weather?

Oh - and I set  "Chances of Super Cell spawning" to '0' and had a pair of crashes that basically said "the number must be positive"

I don't know if other mods may affect Enhanced Weather, but EW is the only weather mod I'm intentionally running.

**Comment by slavens** [comment]
I suppose I should add that we're running MC 1.19.2 and EW v1.0 beta 5

**Comment by TalonFloof** [comment]
the v1.0 version of this mod is not supported, therefore this issue will not be handled, GitHub issues here are only relevant for the rewritten version of this mod.
