### ISSUE TITLE
Suggestion: Weather Station block

### ISSUE THREAD

**Issue by slavens** [Talon396/EnhancedWeather#68]
How hard would it be to add a weather station block to enhance the radar display? Maybe add things like wind speed and direction, maybe a tornado warning? ( a range in blocks on the radar would be cool too)

It'd be cool to have the radar emit a redstone signal when a tornado is 'on the ground'. I'd use it to power the half-dozen village bells in my "city" to get the residents indoors so they don't all die (again, lol).

**Comment by TalonFloof** [comment]
The rewritten version of this mod already does all of this
